pipeline {
    agent any

    environment {
        GITHUB = credentials('GitHub')
        AWS = credentials('AWS')
    }
    stages {
        stage('Build'){
            steps{
                echo 'building...'

            }
        }
        stage('Test'){
            steps{
                echo 'testing...'
            }
        }
        stage('Deploy'){
            steps{
                echo 'deploying...'
            }
        }
    }
}
